openapi: "3.0.1"
info:
  title: "API Documentation"
  description: "This is the API documentation for our Flask app."
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:5000/api"
paths:
  /hello/world:
    get:
      tags:
        - "default"
      summary: "Output hello world."
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                example: 
                  message: "Hello World!!!"
components: {}
